// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeItTrKzxvsxwDi-2Gl4wusEDXQIvfups',
    appId: '1:852004814207:web:1b8582cf14f6f228e42e4a',
    messagingSenderId: '852004814207',
    projectId: 'mindful-fe70d',
    authDomain: 'mindful-fe70d.firebaseapp.com',
    storageBucket: 'mindful-fe70d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAq73X7vBrP6AsjVmSvkb2vSvaD-uiIvI',
    appId: '1:852004814207:android:7e75ae1af084e8bfe42e4a',
    messagingSenderId: '852004814207',
    projectId: 'mindful-fe70d',
    storageBucket: 'mindful-fe70d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLgNiPijP5gYPEOMNVKTXS7pnwoEnZNUU',
    appId: '1:852004814207:ios:7fa5d8bb1590d72fe42e4a',
    messagingSenderId: '852004814207',
    projectId: 'mindful-fe70d',
    storageBucket: 'mindful-fe70d.firebasestorage.app',
    iosBundleId: 'com.example.mindful',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLgNiPijP5gYPEOMNVKTXS7pnwoEnZNUU',
    appId: '1:852004814207:ios:7fa5d8bb1590d72fe42e4a',
    messagingSenderId: '852004814207',
    projectId: 'mindful-fe70d',
    storageBucket: 'mindful-fe70d.firebasestorage.app',
    iosBundleId: 'com.example.mindful',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeItTrKzxvsxwDi-2Gl4wusEDXQIvfups',
    appId: '1:852004814207:web:a496846728565f0ae42e4a',
    messagingSenderId: '852004814207',
    projectId: 'mindful-fe70d',
    authDomain: 'mindful-fe70d.firebaseapp.com',
    storageBucket: 'mindful-fe70d.firebasestorage.app',
  );
}
